### ISSUE TITLE
运行main函数时，在Accuracy初始化时，缺少参数？？请问如何设置

### ISSUE THREAD

**Issue by whper07** [Li-ZK/OSC-SCL#1]
Traceback (most recent call last):
  File "myproject/OSC-SCL-main/main.py", line 15, in <module>
    model = get_model(args, data_info)
  File "myproject/OSC-SCL-main/model/OSC_SCL.py", line 295, in get_model
    model = OSC_SCL(**model_args)
  File "myproject/OSC-SCL-main/model/OSC_SCL.py", line 136, in __init__
    self.train_acc_meter = Accuracy()
TypeError: __new__() missing 1 required positional argument: 'task'

进程已结束,退出代码1

**Comment by Neymar1011** [comment]
> Traceback (most recent call last): File "myproject/OSC-SCL-main/main.py", line 15, in model = get_model(args, data_info) File "myproject/OSC-SCL-main/model/OSC_SCL.py", line 295, in get_model model = OSC_SCL(**model_args) File "myproject/OSC-SCL-main/model/OSC_SCL.py", line 136, in **init** self.train_acc_meter = Accuracy() TypeError: **new**() missing 1 required positional argument: 'task'
> 
> 进程已结束,退出代码1

这边确实是缺少参数的，要根据你的问题来添加
